# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Tony Mihaylova
description: "Hi I'm Tony, and I'm a Data Scientist.  Here is a sample of my recent work.  I come from the world of policy and am convinced that data is essential for smart decisions (both in policy and business world). For more details, below are my Github & LinkedIn pages as well as my resume."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Valletta, Malta"
resume_url: /docs/Tony_Mihaylova_Resume_10_23.pdf
avatar_image: /img/to_upload.JPG

#-------------------------------
# Contact links
linkedln: "https://linkedin.com/in/tmihaylova/" # Add your linkedln handle
github: "https://github.com/tonymih"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

